kubelet_working_dir: /var/lib/kubelet

services_enabled: true
kubelet_modified: false
proxy_modified: false

# List of Kubernetes node binaries to download and install.
kube_node_binaries:
  - kube-proxy
  - kubelet

kubelet_options:
  - "--pod-infra-container-image={{registry_hub}}/google_containers/pause-amd64:3.0"
