---

soa:
#基础平台
  - name: "partner"
    rest: true
    dubbo: true
    project: "base"

  - name: "heartrate"
    rest: true
    dubbo: true
    project: "base"

  - name: "sleep"
    rest: true
    dubbo: true
    project: "base"

  - name: "weight"
    rest: true
    dubbo: true
    project: "base"

  - name: "device"
    rest: true
    dubbo: true
    project: "base"

  - name: "migration"
    rest: true
    dubbo: true
    project: "base"

  - name: "wechatgateway"
    rest: true
    dubbo: true
    project: "base"

  - name: "sport"
    rest: true
    dubbo: true
    project: "base"

  - name: "user"
    rest: true
    dubbo: true
    project: "base"

  - name: "message"
    rest: true
    dubbo: true
    project: "base"

  - name: "devicegateway"
    rest: true
    dubbo: true
    project: "base"

  - name: "websocket"
    rest: false
    dubbo: true
    project: "base"

  - name: "emergencycall"
    rest: true
    dubbo: true
    project: "base"

  - name: "voice"
    rest: true
    dubbo: true
    project: "base"

  - name: "wms"
    rest: true
    dubbo: false
    project: "base"

  - name: "bloodpressure"
    rest: true
    dubbo: true
    project: "base"

  - name: "devicelog"
    rest: true
    dubbo: true
    project: "base"

  - name: "devicesocket"
    rest: true
    dubbo: true
    project: "base"

  - name: "stat"
    rest: true
    dubbo: true
    project: "base"

  - name: "sms"
    rest: true
    dubbo: true
    project: "base"

  - name: "operplatform"
    rest: true
    dubbo: false
    project: "base"

  - name: "supportplatform"
    rest: true
    dubbo: true
    project: "base"

  - name: "events"
    rest: true
    dubbo: true
    project: "base"

  - name: "basis"
    rest: true
    dubbo: true
    project: "base"

  - name: "bloodsugar"
    rest: true
    dubbo: true
    project: "base"

  - name: "tencentgateway"
    rest: true
    dubbo: true
    project: "base"

  - name: "sessions"
    rest: true
    dubbo: true
    project: "base"

  - name: "pay"
    rest: true
    dubbo: true
    project: "base"

  - name: "order"
    rest: false
    dubbo: true
    project: "base"

#运动项目
  - name: "commons"
    rest: true
    dubbo: true
    project: "sports"

  - name: "enterprisemanager"
    rest: true
    dubbo: false
    project: "sports"

  - name: "personalgroup"
    rest: true
    dubbo: true
    project: "sports"

  - name: "enterprisegroup"
    rest: true
    dubbo: true
    project: "sports"

  - name: "challenge"
    rest: true
    dubbo: true
    project: "sports"

  - name: "contest"
    rest: true
    dubbo: true
    project: "sports"

  - name: "marketing"
    rest: true
    dubbo: true
    project: "sports"

  - name: "trace"
    rest: true
    dubbo: true
    project: "sports"

  - name: "prescription"
    rest: true
    dubbo: true
    project: "sports"

#健康项目
  - name: "schedule"
    rest: true
    dubbo: true
    project: "health"

  - name: "followup"
    rest: true
    dubbo: true
    project: "health"

  - name: "doctor"
    rest: true
    dubbo: true
    project: "health"

  - name: "im"
    rest: true
    dubbo: true
    project: "health"

  - name: "patient"
    rest: true
    dubbo: true
    project: "health"

  - name: "healthmanagement"
    rest: true
    dubbo: false
    project: "health"

  - name: "abnormal"
    rest: true
    dubbo: true
    project: "health"

  - name: "datachart"
    rest: true
    dubbo: false
    project: "health"

  - name: "sysmessage"
    rest: true
    dubbo: true
    project: "health"

  - name: "statistics"
    rest: true
    dubbo: true
    project: "health"

  - name: "health"
    rest: true
    dubbo: true
    project: "health"

  - name: "datamigration"
    rest: true
    dubbo: true
    project: "health"

  - name: "healthoperation"
    rest: true
    dubbo: true
    project: "health"

  - name: "datacollection"
    rest: false
    dubbo: true
    project: "health"

#开放平台
  - name: "deviceopenapi"
    rest: true
    dubbo: true
    project: "open"

  - name: "openapi"
    rest: true
    dubbo: true
    project: "open"

#医生服务
  - name: "doctorapp"
    rest: true
    dubbo: false
    project: "doctor"

  - name: "feedback"
    rest:  false
    dubbo: true
    project: "doctor"

  - name: "doctordevice"
    rest:  true
    dubbo: false
    project: "doctor"

  - name: "sim"
    rest:  false
    dubbo: true
    project: "doctor"

  - name: "assistant"
    rest:  true
    dubbo: false
    project: "doctor"

  - name: "temperature"
    rest:  true
    dubbo: true
    project: "doctor"

#产线系统
  - name: "pms"
    rest:  true
    dubbo: false
    project: "pms"