apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: confluence-mysql-v5.6
  namespace: ops
  labels:
    ops-app: confluence-mysql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        ops-app: confluence-mysql
    spec:
      containers:
      - image: 10.10.185.222/mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: WUmhugJbNzefe6Vt
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: confluence-mysql