---
- name:
  set_fact:
    hostname: "{{ ansible_default_ipv4.address|regex_replace('\\.','-')}}"
  tags: env7

- name: set /etc/sysconfig/network
  template: src=network.j2 dest=/etc/sysconfig/network
  tags: env7

- name: set /etc/hosts
  lineinfile: dest=/etc/hosts regexp="127.0.0.1 {{hostname}}" state=absent
  tags: env7

- name: set /etc/hosts
  lineinfile: dest=/etc/hosts regexp="^{{ansible_default_ipv4.address}} {{hostname}}$" line="{{ansible_default_ipv4.address}} {{hostname}}"
  tags: env7

- name: hostnamectl --static set-hostname {{hostname}}
  shell: hostnamectl --static set-hostname {{hostname}}
  ignore_errors: yes
  tags: env7

- name: set /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  tags: env7