---
- name:
  set_fact:
    hostname: "{{ ansible_default_ipv4.address|regex_replace('\\.','-')}}"
  tags: env7

- name:
  template: src=network.j2 dest=/etc/sysconfig/network
  tags: env7

- name:
  lineinfile: dest=/etc/hosts regexp="127.0.0.1 {{hostname}}" state=absent
  tags: env7

- name:
  lineinfile: dest=/etc/hosts regexp="^{{ansible_default_ipv4.address}} {{hostname}}$" line="{{ansible_default_ipv4.address}} {{hostname}}"
  tags: env7

- name:
  shell: hostname {{hostname}}
  ignore_errors: yes
  tags: env7