---

- name: Setting the etcd_modified fact to true
  set_fact:
    etcd_conf_dir: "/etc/etcd"
  when: etcd_source_type == "package-manager"

- name: Create etcd config directory
  file: path="{{ etcd_conf_dir }}" state=directory

- include: etcd-configure.yml

- include: firewalld-configure.yml
  when: has_firewalld

- include: iptables-configure.yml
  when: not has_firewalld and has_iptables
