---
- name: Download tar file
  get_url:
    url: "{{ etcd_download_url }}"
    dest: "{{ ansible_temp_dir }}"
    validate_certs: False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"

- name: Extract tar file
  unarchive:
    src: "{{ ansible_temp_dir }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: "{{ ansible_temp_dir }}/"
    copy: no

- name: Create etcd config directory
  file: path="{{ etcd_script_dir }}" state=directory

- name: copy etcd bin file
  command: "/bin/cp -a {{ ansible_temp_dir }}/etcd-v{{ etcd_version }}-linux-amd64/{{ item }} {{etcd_script_dir}}/"
  with_items:
    - etcd
    - etcdctl

- name: Create symlinks
  file:
    src: "{{etcd_script_dir}}/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
    - etcd
    - etcdctl

