---
# Install Flannel.

- name: Install Flannel with github release
  include: github-release.yml
  when: flannel_source_type == "github-release"

- name: Create config file directory
  file: path={{ flannel_config_dir }} state=directory

- name: Install Flannel config file
  template: src=flannel.j2 dest={{ flannel_config_dir }}/flannel
  notify:
    - restart flannel
