kube_version: 1.6.1
kube_source_type: github-release
kube_master_api_port: 6443
kube_script_dir: /opt/kubernetes/bin
kube_config_dir: /opt/kubernetes/cfg

kube_cert_group: kube-cert
kube_cert_dir: "/srv/kubernetes"
kube_cert_ip: "{{ hostvars[inventory_hostname]['ansible_all_ipv4_addresses'] | join (',IP:') }}"
kube_token_dir: "{{ kube_cert_dir }}/tokens"
dns_domain: "{{ cluster_name }}"
dns_server: "{{ kube_service_addresses|ipaddr('net')|ipaddr(10)|ipaddr('address') }}"

#kube_download_ur: https://storage.googleapis.com/kubernetes-release/release/v{{kube_version}}
kube_download_ur: http://10.10.119.24/ansible



kube_releases_directory: /opt/kubernetes
kube_current_release_directory: "{{ kube_releases_directory }}/{{ kube_version }}"
kube_manifest_dir: "{{ kube_config_dir }}/manifests"


