---

- include: secrets.yml
  tags:
    - secrets
    - configure

- name:
  file: path=/data/logs state=directory

- name:
  file: path="{{kube_logs_directory}}" state=directory

- name: install ceph-common
  include: ceph-common.yml
