---

- include: secrets.yml
  tags:
    - secrets
    - configure

- name: config dns
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name:
  file: path=/data/logs state=directory

- name:
  file: path="{{kube_logs_directory}}" state=directory