---
- name: Get the node token values
  slurp:
    src: "{{ kube_token_dir }}/{{ item }}.token"
  with_items:
    - "system:kubelet-bootstrap"
  register: tokens
  delegate_to: "{{ groups['masters'][0] }}"

- name: Set token facts
  set_fact:
    bootstrap_token: "{{ tokens.results[0].content|b64decode }}"

