---
- name: Add k8s Systemd Unit File
  template: src="{{ item }}.service.j2" dest="/usr/lib/systemd/system/{{ item }}.service"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: reload systemd
  command: systemctl daemon-reload