---

- name: Install docker
  include: install.yml
  tags: install

- name: configure docker
  include: configure.yml
  tags: install

- name: Enable docker
  service: name=docker enabled=yes

- name: Start docker
  service: name=docker state=started