---
- name: LOGGING | Assures {{ kube_addons_dir }}/cluster-logging dir exists
  file: path={{ kube_addons_dir }}/cluster-logging state=directory

- name: LOGGING | Copy logging manifests to master
  template:
  args:
    src: "cluster-logging/{{ item }}.j2"
    dest: "{{ kube_addons_dir }}/cluster-logging/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - kibana-controller.yaml
    - kibana-service.yaml
    - fluentd-es-ds.yaml
    - es-statefulsets.yaml
