- name: lifesense | Assures {{ kube_addons_dir }}/lifesense dir exists
  file: path={{ kube_addons_dir }}/lifesense state=directory
  tags: k8s-config

- name: lifesense | Assures {{ kube_addons_dir }}/lifesense/{{lifesense_env}} dir exists
  file: path={{ kube_addons_dir }}/lifesense/{{lifesense_env}} state=directory
  tags: k8s-config

- name: 
  template: src="lifesense/lifesense-limits.yaml" dest="{{ kube_addons_dir }}/lifesense/lifesense-limits.yaml"
  tags: k8s-config

- name: 
  template: src="lifesense/lifesense-cm.yaml" dest="{{ kube_addons_dir }}/lifesense/{{lifesense_env}}/lifesense-cm.yaml"
  tags: k8s-config

- name: 
  template: src="lifesense/lifesense-ns.yaml" dest="{{ kube_addons_dir }}/lifesense/{{lifesense_env}}/lifesense-ns.yaml"
  tags: k8s-config

- name: lifesense | Assures {{ kube_addons_dir }}/lifesense/ingress dir exists
  file: path={{ kube_addons_dir }}/lifesense/ingress state=directory
  tags: k8s-config

- name:
  template: src="lifesense/lifesense-ingress.yaml" dest="{{ kube_addons_dir }}/lifesense/ingress/{{item}}-ingress.yaml"
  with_items:
  - "health-qa.lifesense.com"
  - "sports-qa.lifesense.com"
  - "health-qa2.lifesense.com"
  - "sports-qa2.lifesense.com"
  tags: k8s-config

- name: lifesense | Assures {{ kube_addons_dir }}/lifesense/svc dir exists
  file: path={{ kube_addons_dir }}/lifesense/svc state=directory
  tags: k8s-config

- name:
  template: src="lifesense/lifesense-svc.yaml" dest="{{ kube_addons_dir }}/lifesense/svc/{{item.name}}-svc.yaml"
  when: item.rest
  with_items: "{{soa}}"
  tags: k8s-config

- name: lifesense | Assures {{ kube_addons_dir }}/lifesense/soa dir exists
  file: path={{ kube_addons_dir }}/lifesense/soa state=directory
  tags: k8s-config

- name:
  template: src="lifesense/lifesense-controller.yaml" dest="{{ kube_addons_dir }}/lifesense/soa/{{item.name}}-controller.yaml"
  with_items: "{{soa}}"
  tags: k8s-config