- name: lifesense | Assures {{ kube_addons_dir }}/lifesense dir exists
  file: path={{ kube_addons_dir }}/lifesense state=directory
  tags: k8s-config

- name: lifesense | Assures {{ kube_addons_dir }}/lifesense/{{lifesense_env}} dir exists
  file: path={{ kube_addons_dir }}/lifesense/{{lifesense_env}} state=directory
  tags: k8s-config

- name: 
  template: src="lifesense/rq-limits.yaml.j2" dest="{{ kube_addons_dir }}/lifesense/rq-limits.yaml"
  tags: k8s-config

- name: 
  template: src="lifesense/env-cm.yaml.j2" dest="{{ kube_addons_dir }}/lifesense/{{lifesense_env}}/env-cm.yaml"
  tags: k8s-config

- name: 
  template: src="lifesense/lifesense-ns.yaml.j2" dest="{{ kube_addons_dir }}/lifesense/{{lifesense_env}}/lifesense-ns.yaml"
  tags: k8s-config

- name:
  template: src="lifesense/lifesense-ingress.yaml.j2" dest="{{ kube_addons_dir }}/lifesense/lifesense-ingress.yaml"
  tags: k8s-config

- name: lifesense | Assures {{ kube_addons_dir }}/lifesense/svc dir exists
  file: path={{ kube_addons_dir }}/lifesense/svc state=directory
  tags: k8s-config

- name:
  template: src="lifesense/rest-service.yaml.j2" dest="{{ kube_addons_dir }}/lifesense/svc/{{item.name}}-svc.yaml"
  when: item.rest
  with_items: "{{soa}}"
  tags: k8s-config

- name: lifesense | Assures {{ kube_addons_dir }}/lifesense/soa dir exists
  file: path={{ kube_addons_dir }}/lifesense/soa state=directory
  tags: k8s-config

- name:
  template: src="lifesense/lifesense-controller.yaml.j2" dest="{{ kube_addons_dir }}/lifesense/soa/{{item.name}}-controller.yaml"
  with_items: "{{soa}}"
  tags: k8s-config