---
- name: Assures addons dir exists
  file: path={{ kube_addons_dir }} state=directory

- include: generic-install.yml
  when: not is_atomic and not is_coreos

- name: Assures local addon dir exists
  local_action: file
    path={{ local_temp_addon_dir }}
    state=directory
  become: no

- include: dns.yml
  when: dns_setup

- include: cluster-monitoring.yml
  when: cluster_monitoring

- include: cluster-logging.yml
  when: cluster_logging

- include: kube-dash.yml
  when: kube_dash

- include: rbd.yml

- include: node-problem-detector.yml

- include: ingress.yml